name: Sync from osu! upstream

# Workflow dispatch can take inputs like any other github.event
# As part of #5090 - we should evaluate adding inputs and outputs to refine this.
on:
  workflow_dispatch:
    inputs:
      backup:
        description: "Create a backup of your target branch? (true/false)"
        required: true
        default: "false"
      force:
        description: "Overwrite any changes in the target repository? (true/false)"
        required: true
        default: "false"

jobs:
  sync:
    name: Execute Sync Task
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure Git to use your name
        shell: bash
        run: |
          set -eo pipefail

          #FIXME: We're using the noreply email of GitHub for now. Let's figure out a way to get the committer's email.
          git config --global user.name ${{ github.actor }}
          git config --global user.email ${{ github.actor }}@users.noreply.github.com


      - name: Begin Pull Task
        shell: bash
        run: |
         set -eo pipefail

         # sanitize github input into boolean
         # https://stackoverflow.com/questions/14700579/bash-converting-string-to-boolean-variable
         function boolean () {
            case $1 in
              true) echo true ;;
              false) echo false ;;
              *) echo "Unknown operand \"$1\"" 1>&2; exit 1 ;;
            esac
         }

         #Upstream repository URL, this is where everything ties down.
         UPSTREAM_REPO="https://github.com/ppy/osu-wiki"
         BACKUP_BRANCH_NAME="backup-$(git branch --show-current)"
         BRANCH_NAME="$(git branch --show-current)"

         git remote add upstream $UPSTREAM_REPO
         git fetch upstream

         # User has no confidence in our git skills, so let's backup when needed!
         if [ $(boolean ${{ github.event.inputs.backup }}) ]; then
          git branch $BACKUP_BRANCH_NAME
          git push -u origin $BACKUP_BRANCH_NAME
         fi

         if [ ! $(boolean ${{ github.event.inputs.force }}) ]; then
           git merge upstream/master --commit -m "Merge upstream/master changes to $BRANCH_NAME.";
           git push origin +$BRANCH_NAME
         else
           echo "::warning::You've set force-overwriting to true. This will overwrite your changes."
           git reset --hard upstream/master
           git pull upstream master
           git push origin +$BRANCH_NAME
          fi

# MAINTAINERS: Uncomment this so you can debug your workflow session if something goes bad.
#
#      - name: Execute SSH Debug
#        uses: mxschmitt/action-tmate@master
#        with:
#            sudo: true
#        if: ${{ failure() }}
#        timeout-minutes: 120
